name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm i -g pnpm@8.11.0
      - run: pnpm i
      - run: pnpm build

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: pnpm publish --access public --no-git-checks
